/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AiLaTrieuPhu;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author ADMIN PC
 */
public class ALTP extends javax.swing.JFrame {

    /**
     * Creates new form ALTP
     */
    public ALTP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnbatdau = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        manhinhchobatdau = new javax.swing.JLabel();
        Anhwin = new javax.swing.JLabel();
        AnhLose = new javax.swing.JLabel();
        txtsocauhoi = new javax.swing.JLabel();
        pnkhangia = new javax.swing.JPanel();
        lbphantramD = new javax.swing.JLabel();
        lbphantramC = new javax.swing.JLabel();
        lbphantramB = new javax.swing.JLabel();
        lbphantramA = new javax.swing.JLabel();
        jProgressBarD = new javax.swing.JProgressBar();
        jProgressBarC = new javax.swing.JProgressBar();
        jProgressBarB = new javax.swing.JProgressBar();
        jProgressBarA = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        btnkhangia = new javax.swing.JLabel();
        btn50 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        btntiep = new javax.swing.JButton();
        btndung = new javax.swing.JButton();
        txtdap1 = new javax.swing.JButton();
        txtdap2 = new javax.swing.JButton();
        txtdap3 = new javax.swing.JButton();
        txtdap4 = new javax.swing.JButton();
        txtcauhoi = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ai Là Triệu Phú");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnbatdau.setBackground(new java.awt.Color(102, 0, 255));
        btnbatdau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnbatdau.setForeground(new java.awt.Color(255, 255, 255));
        btnbatdau.setText("Bắt Đầu");
        btnbatdau.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                btnbatdauComponentHidden(evt);
            }
        });
        btnbatdau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatdauActionPerformed(evt);
            }
        });
        getContentPane().add(btnbatdau, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 149, 65));

        btnthoat.setBackground(new java.awt.Color(102, 0, 255));
        btnthoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnthoat.setForeground(new java.awt.Color(255, 255, 255));
        btnthoat.setText("Thoát");
        btnthoat.setName(""); // NOI18N
        btnthoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnthoatMouseClicked(evt);
            }
        });
        getContentPane().add(btnthoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 150, 63));

        manhinhchobatdau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AiLaTrieuPhu/anhgame/hinhanhmanhinhcho.gif"))); // NOI18N
        getContentPane().add(manhinhchobatdau, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Anhwin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Anhwin.setForeground(new java.awt.Color(255, 255, 255));
        Anhwin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AiLaTrieuPhu/anhgame/giaodienchienthang_new.gif"))); // NOI18N
        Anhwin.setToolTipText("");
        getContentPane().add(Anhwin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -3, 430, 520));

        AnhLose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AnhLose.setForeground(new java.awt.Color(255, 255, 255));
        AnhLose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AiLaTrieuPhu/anhgame/giaodienthua_new.gif"))); // NOI18N
        AnhLose.setToolTipText("");
        getContentPane().add(AnhLose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -3, 430, 520));

        txtsocauhoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsocauhoi.setForeground(new java.awt.Color(255, 255, 51));
        txtsocauhoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtsocauhoi.setText("Câu Hỏi Số  ");
        txtsocauhoi.setToolTipText("");
        getContentPane().add(txtsocauhoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 170, 40));

        pnkhangia.setBackground(new Color(0,0,0,64));
        pnkhangia.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 153)));
        pnkhangia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbphantramD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbphantramD.setForeground(new java.awt.Color(255, 255, 255));
        lbphantramD.setText("jLabel3");
        pnkhangia.add(lbphantramD, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        lbphantramC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbphantramC.setForeground(new java.awt.Color(255, 255, 255));
        lbphantramC.setText("jLabel3");
        pnkhangia.add(lbphantramC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        lbphantramB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbphantramB.setForeground(new java.awt.Color(255, 255, 255));
        lbphantramB.setText("jLabel3");
        pnkhangia.add(lbphantramB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        lbphantramA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbphantramA.setForeground(new java.awt.Color(255, 255, 255));
        lbphantramA.setText("jLabel3");
        pnkhangia.add(lbphantramA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));
        pnkhangia.add(jProgressBarD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 90, -1));
        pnkhangia.add(jProgressBarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 90, -1));
        pnkhangia.add(jProgressBarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 90, -1));
        pnkhangia.add(jProgressBarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AiLaTrieuPhu/anhgame/binhcon.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        pnkhangia.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 160));

        getContentPane().add(pnkhangia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 330, 160));

        btnkhangia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AiLaTrieuPhu/anhgame/khangia1.gif"))); // NOI18N
        btnkhangia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkhangiaMouseClicked(evt);
            }
        });
        getContentPane().add(btnkhangia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, 40));

        btn50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AiLaTrieuPhu/anhgame/501.gif"))); // NOI18N
        btn50.setIconTextGap(5);
        btn50.setPreferredSize(new java.awt.Dimension(80, 80));
        btn50.setRequestFocusEnabled(false);
        btn50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn50MouseClicked(evt);
            }
        });
        getContentPane().add(btn50, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 50, 40));

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 102));
        jProgressBar1.setForeground(new java.awt.Color(255, 255, 102));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 335, 10));

        btntiep.setBackground(new java.awt.Color(102, 0, 255));
        btntiep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntiep.setForeground(new java.awt.Color(255, 255, 255));
        btntiep.setText("Đi Tiếp ->");
        btntiep.setName(""); // NOI18N
        btntiep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntiepMouseClicked(evt);
            }
        });
        btntiep.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                btntiepComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btntiepComponentShown(evt);
            }
        });
        getContentPane().add(btntiep, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 150, 63));

        btndung.setBackground(new java.awt.Color(102, 0, 255));
        btndung.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndung.setForeground(new java.awt.Color(255, 255, 255));
        btndung.setText("Dừng");
        btndung.setName(""); // NOI18N
        btndung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndungMouseClicked(evt);
            }
        });
        getContentPane().add(btndung, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 150, 63));

        txtdap1.setBackground(new java.awt.Color(102, 0, 255));
        txtdap1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdap1.setForeground(new java.awt.Color(255, 255, 255));
        txtdap1.setText("dap1");
        txtdap1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtdap1.setName(""); // NOI18N
        txtdap1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdap1MouseClicked(evt);
            }
        });
        txtdap1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                txtdap1ComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txtdap1ComponentShown(evt);
            }
        });
        getContentPane().add(txtdap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 190, 40));

        txtdap2.setBackground(new java.awt.Color(102, 0, 255));
        txtdap2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdap2.setForeground(new java.awt.Color(255, 255, 255));
        txtdap2.setText("dap2");
        txtdap2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtdap2.setName(""); // NOI18N
        txtdap2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdap2MouseClicked(evt);
            }
        });
        getContentPane().add(txtdap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 190, 40));

        txtdap3.setBackground(new java.awt.Color(102, 0, 255));
        txtdap3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdap3.setForeground(new java.awt.Color(255, 255, 255));
        txtdap3.setText("dap3");
        txtdap3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtdap3.setName(""); // NOI18N
        txtdap3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdap3MouseClicked(evt);
            }
        });
        getContentPane().add(txtdap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 190, 40));

        txtdap4.setBackground(new java.awt.Color(102, 0, 255));
        txtdap4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdap4.setForeground(new java.awt.Color(255, 255, 255));
        txtdap4.setText("dap4");
        txtdap4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtdap4.setName(""); // NOI18N
        txtdap4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdap4MouseClicked(evt);
            }
        });
        getContentPane().add(txtdap4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 190, 40));

        txtcauhoi.setEditable(false);
        txtcauhoi.setBackground(new java.awt.Color(153, 153, 255));
        txtcauhoi.setColumns(20);
        txtcauhoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtcauhoi.setForeground(new java.awt.Color(255, 255, 255));
        txtcauhoi.setLineWrap(true);
        txtcauhoi.setRows(5);
        txtcauhoi.setText("                           Bắt Đầu Đi Nào !");
        txtcauhoi.setWrapStyleWord(true);
        txtcauhoi.setAutoscrolls(false);
        txtcauhoi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtcauhoi.setCaretColor(new java.awt.Color(153, 153, 255));
        txtcauhoi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtcauhoi.setDisabledTextColor(new java.awt.Color(255, 255, 51));
        txtcauhoi.setDoubleBuffered(true);
        txtcauhoi.setDragEnabled(true);
        txtcauhoi.setEnabled(false);
        txtcauhoi.setOpaque(false);
        txtcauhoi.setBackground(new Color(0,0,0,0));
        getContentPane().add(txtcauhoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 335, 83));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AiLaTrieuPhu/anhgame/anhnenba2.gif"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -3, 430, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/// Sự Kiện -----------------------------------------------*****
    private void btnbatdauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatdauActionPerformed
        clip.stop();
        NguoiChoiSanSang();
        timecho = new Timer(60, new LoadTimeVaoGame());
        timecho.start();
        btnbatdau.setEnabled(false);
        manhinhchobatdau.setVisible(true);
//        try {
//            TimeUnit.SECONDS.sleep(7);
//        } catch (InterruptedException ex) {
//            Logger.getLogger(ALTP.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        listold.clear();
//        Giaithuong = 0;
//        diem = 1;
//        camung50 = 0;
//        btnbatdau.setVisible(false);
//        btnthoat.setVisible(false);
//        btntiep.setVisible(false);
//        btndung.setVisible(false);
//        btntiep.setVisible(false);
//        btn50.setVisible(true);
//        btnkhangia.setVisible(true);
//        /// an 2 cai win voi lose
//        Anhwin.setVisible(false);
//        AnhLose.setVisible(false);
    }//GEN-LAST:event_btnbatdauActionPerformed

    private void btnthoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnthoatMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnthoatMouseClicked

    private void txtdap2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdap2MouseClicked
        clipcauhoi.stop();
        clipnhacnen.stop();
        time.stop();
        pnkhangia.setVisible(false);
        thoigian = 100;
        traloi = "dap2";
        if (traloi.equals(list1.listch.get(a).getKetqua())) {
            Win();
            txtdap1.setVisible(false);
            txtdap2.setVisible(false);
            txtdap3.setVisible(false);
            txtdap4.setVisible(false);
            diem++;
            Giaithuong = Giaithuong + 200 * listold.size();
            txtcauhoi.setText("      Vượt Câu " + listold.size() + " - Số Tiền Thưởng Hiện Tại \n - > " + Giaithuong + "$");
            btntiep.setVisible(true);
            if (diem > 5) {
                btndung.setVisible(true);
            }
            jProgressBar1.setVisible(false);
            ChienThangTroChoi();
        } else {
            ThuaTrochoi();
        }
    }//GEN-LAST:event_txtdap2MouseClicked
// khu khi mo form 
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtdap1.setVisible(false);
        txtdap2.setVisible(false);
        txtdap3.setVisible(false);
        txtdap4.setVisible(false);
        btntiep.setVisible(false);
        btndung.setVisible(false);
        btn50.setVisible(false);
        btnkhangia.setVisible(false);
        jProgressBar1.setVisible(false);
        jProgressBar1.setValue(100);
        pnkhangia.setVisible(false);
        txtsocauhoi.setVisible(false);
        /// an 2 cai win voi lose
        Anhwin.setVisible(false);
        AnhLose.setVisible(false);
        ///an man hinh cho
        manhinhchobatdau.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void txtdap1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdap1MouseClicked
        clipcauhoi.stop();
        clipnhacnen.stop();
        time.stop();
        pnkhangia.setVisible(false);
        thoigian = 100;
        traloi = "dap1";
        if (traloi.equals(list1.listch.get(a).getKetqua())) {
            Win();
            txtdap1.setVisible(false);
            txtdap2.setVisible(false);
            txtdap3.setVisible(false);
            txtdap4.setVisible(false);
            jProgressBar1.setVisible(false);
            diem++;
            Giaithuong = Giaithuong + 200 * listold.size();
            txtcauhoi.setText("      Vượt Câu " + listold.size() + " - Số Tiền Thưởng Hiện Tại \n - > " + Giaithuong + "$");
            btntiep.setVisible(true);
            if (diem > 5) {
                btndung.setVisible(true);
            }
            jProgressBar1.setVisible(false);
            ChienThangTroChoi();
        } else {
            ThuaTrochoi();
        }
    }//GEN-LAST:event_txtdap1MouseClicked

    private void txtdap3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdap3MouseClicked
        clipcauhoi.stop();
        clipnhacnen.stop();
        time.stop();
        pnkhangia.setVisible(false);
        thoigian = 100;
        traloi = "dap3";
        if (traloi.equals(list1.listch.get(a).getKetqua())) {
            Win();
            txtdap1.setVisible(false);
            txtdap2.setVisible(false);
            txtdap3.setVisible(false);
            txtdap4.setVisible(false);
            jProgressBar1.setVisible(false);
            diem++;
            Giaithuong = Giaithuong + 200 * listold.size();
            txtcauhoi.setText("      Vượt Câu " + listold.size() + " - Số Tiền Thưởng Hiện Tại \n - > " + Giaithuong + "$");
            btntiep.setVisible(true);
            if (diem > 5) {
                btndung.setVisible(true);
            }
            jProgressBar1.setVisible(false);
            ChienThangTroChoi();
        } else {
            ThuaTrochoi();
        }
    }//GEN-LAST:event_txtdap3MouseClicked

    private void txtdap4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdap4MouseClicked
        clipcauhoi.stop();
        clipnhacnen.stop();
        time.stop();
        pnkhangia.setVisible(false);
        thoigian = 100;
        traloi = "dap4";
        if (traloi.equals(list1.listch.get(a).getKetqua())) {
            Win();
            txtdap1.setVisible(false);
            txtdap2.setVisible(false);
            txtdap3.setVisible(false);
            txtdap4.setVisible(false);
            jProgressBar1.setVisible(false);
            diem++;
            Giaithuong = Giaithuong + 200 * listold.size();
            txtcauhoi.setText("      Vượt Câu " + listold.size() + " - Số Tiền Thưởng Hiện Tại \n - > " + Giaithuong + "$");
            btntiep.setVisible(true);
            if (diem > 5) {
                btndung.setVisible(true);
            }
            jProgressBar1.setVisible(false);
            ChienThangTroChoi();
        } else {
            ThuaTrochoi();
        }
    }//GEN-LAST:event_txtdap4MouseClicked

    private void btndungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndungMouseClicked
        Chienthang();
        time.stop();
        clipwin.stop();
        txtcauhoi.setText("Bạn Đã Ra Về Với Tiền Thưởng " + Giaithuong + "$");
        btnbatdau.setVisible(true);
        btndung.setVisible(false);
        btnthoat.setVisible(true);
        btntiep.setVisible(false);
        btn50.setVisible(false);
        btnkhangia.setVisible(false);
    }//GEN-LAST:event_btndungMouseClicked

    private void btnbatdauComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnbatdauComponentHidden
        clipss.stop();
        txtdap1.setVisible(true);
        txtdap2.setVisible(true);
        txtdap3.setVisible(true);
        txtdap4.setVisible(true);
        jProgressBar1.setVisible(true);
        a = TimSoKhac();
        DocCauhoi(list1, a);
        NhacNen();
        time = new Timer(300, new LoadTime());
        time.start();
        txtcauhoi.setText(list1.listch.get(a).getCauhoi());
        txtdap1.setText(list1.listch.get(a).getDap1());
        txtdap2.setText(list1.listch.get(a).getDap2());
        txtdap3.setText(list1.listch.get(a).getDap3());
        txtdap4.setText(list1.listch.get(a).getDap4());
        txtsocauhoi.setText("Câu Hỏi Thứ " + listold.size());
        txtsocauhoi.setVisible(true);
    }//GEN-LAST:event_btnbatdauComponentHidden

    private void btn50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn50MouseClicked
        if (txtdap1.isVisible() == true) {
            Win();
            btn50.setVisible(false);
            if (list1.listch.get(a).getKetqua().equals("dap1")) {
                txtdap2.setVisible(false);
                txtdap3.setVisible(false);
            } else if (list1.listch.get(a).getKetqua().equals("dap2")) {
                txtdap1.setVisible(false);
                txtdap3.setVisible(false);
            } else if (list1.listch.get(a).getKetqua().equals("dap3")) {
                txtdap2.setVisible(false);
                txtdap1.setVisible(false);
            } else if (list1.listch.get(a).getKetqua().equals("dap4")) {
                txtdap1.setVisible(false);
                txtdap2.setVisible(false);
            }
            btn50.setVisible(false);
            camung50 = 1;
            thoigian = 100;
        }
    }//GEN-LAST:event_btn50MouseClicked

    private void btnkhangiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkhangiaMouseClicked
        if (txtdap1.isVisible() == true || txtdap2.isVisible() == true || txtdap3.isVisible() == true || txtdap4.isVisible() == true) {
            Win();
            jProgressBarA.setVisible(true);
            jProgressBarB.setVisible(true);
            jProgressBarC.setVisible(true);
            jProgressBarD.setVisible(true);
            lbphantramA.setVisible(true);
            lbphantramB.setVisible(true);
            lbphantramC.setVisible(true);
            lbphantramB.setVisible(true);
            int A, B, C, D;
            btnkhangia.setVisible(false);
            thoigian = 100;
            pnkhangia.setVisible(true); ///hien cai binh chon len 
            Random rd = new Random();
            jProgressBarA.setValue(rd.nextInt(100) + 1);
            A = jProgressBarA.getValue();
            jProgressBarB.setValue(rd.nextInt(100 - A));
            B = jProgressBarB.getValue();
            jProgressBarC.setValue(rd.nextInt(100 - A - B));
            C = jProgressBarC.getValue();
            jProgressBarD.setValue(100 - (A + B + C));
            D = jProgressBarD.getValue();
            lbphantramA.setText("" + A + "%");
            lbphantramB.setText("" + B + "%");
            lbphantramC.setText("" + C + "%");
            lbphantramD.setText("" + D + "%");
            if (camung50 == 1) {
                if (list1.listch.get(a).getKetqua().equals("dap1")) {
                    jProgressBarA.setValue(rd.nextInt(100) + 1);
                    A = jProgressBarA.getValue();
                    jProgressBarD.setValue(100 - jProgressBarA.getValue());
                    D = jProgressBarD.getValue();
                    lbphantramA.setText("" + A + "%");
                    lbphantramD.setText("" + D + "%");
                    jProgressBarB.setVisible(false);
                    lbphantramB.setVisible(false);
                    jProgressBarC.setVisible(false);
                    lbphantramC.setVisible(false);
                } else if (list1.listch.get(a).getKetqua().equals("dap2")) {
                    jProgressBarB.setValue(rd.nextInt(100) + 1);
                    B = jProgressBarB.getValue();
                    jProgressBarD.setValue(100 - jProgressBarB.getValue());
                    D = jProgressBarD.getValue();
                    lbphantramB.setText("" + B + "%");
                    lbphantramD.setText("" + D + "%");
                    jProgressBarA.setVisible(false);
                    lbphantramA.setVisible(false);
                    jProgressBarC.setVisible(false);
                    lbphantramC.setVisible(false);
                } else if (list1.listch.get(a).getKetqua().equals("dap3")) {
                    jProgressBarC.setValue(rd.nextInt(100) + 1);
                    C = jProgressBarC.getValue();
                    jProgressBarD.setValue(100 - jProgressBarC.getValue());
                    D = jProgressBarD.getValue();
                    lbphantramC.setText("" + C + "%");
                    lbphantramD.setText("" + D + "%");
                    jProgressBarA.setVisible(false);
                    lbphantramA.setVisible(false);
                    jProgressBarB.setVisible(false);
                    lbphantramB.setVisible(false);
                } else if (list1.listch.get(a).getKetqua().equals("dap4")) {
                    jProgressBarC.setValue(rd.nextInt(100) + 1);
                    C = jProgressBarC.getValue();
                    jProgressBarD.setValue(100 - jProgressBarC.getValue());
                    D = jProgressBarD.getValue();
                    lbphantramC.setText("" + C + "%");
                    lbphantramD.setText("" + D + "%");
                    jProgressBarA.setVisible(false);
                    lbphantramA.setVisible(false);
                    jProgressBarB.setVisible(false);
                    lbphantramB.setVisible(false);
                }
                camung50 = 0;
            }
        }
    }//GEN-LAST:event_btnkhangiaMouseClicked

    private void btntiepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntiepMouseClicked
        clipwin.stop();
        txtdap1.setVisible(true);
        txtdap2.setVisible(true);
        txtdap3.setVisible(true);
        txtdap4.setVisible(true);
        jProgressBar1.setVisible(true);
        a = TimSoKhac();
        DocCauhoi(list1, a);
        NhacNen();
        time = new Timer(300, new LoadTime());
        time.start();
        txtcauhoi.setText(list1.listch.get(a).getCauhoi());
        txtdap1.setText(list1.listch.get(a).getDap1());
        txtdap2.setText(list1.listch.get(a).getDap2());
        txtdap3.setText(list1.listch.get(a).getDap3());
        txtdap4.setText(list1.listch.get(a).getDap4());
        btndung.setVisible(false);
        btntiep.setVisible(false);
        camung50 = 0;
        txtsocauhoi.setText("Câu Hỏi Thứ " + listold.size());
    }//GEN-LAST:event_btntiepMouseClicked
//// su li bug
    private void txtdap1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtdap1ComponentHidden
        btnbatdau.setEnabled(true);
        btnthoat.setEnabled(true);
        btntiep.setEnabled(true);
        btndung.setEnabled(true);
    }//GEN-LAST:event_txtdap1ComponentHidden

    private void txtdap1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtdap1ComponentShown
        btnbatdau.setEnabled(false);
        btnthoat.setEnabled(false);
        btntiep.setEnabled(false);
        btndung.setEnabled(false);
    }//GEN-LAST:event_txtdap1ComponentShown

    private void btntiepComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btntiepComponentShown
        txtdap1.setEnabled(false);
        txtdap2.setEnabled(false);
        txtdap3.setEnabled(false);
        txtdap4.setEnabled(false);
    }//GEN-LAST:event_btntiepComponentShown

    private void btntiepComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btntiepComponentHidden
        txtdap1.setEnabled(true);
        txtdap2.setEnabled(true);
        txtdap3.setEnabled(true);
        txtdap4.setEnabled(true);
    }//GEN-LAST:event_btntiepComponentHidden

    /**
     * @param args the command line arguments
     */
    ///bat dau chuong trinh 
    private static Clip clip;

    private static void batdau() {
        try {
            Scanner sc = new Scanner(System.in);
            File file = new File("src/AiLaTrieuPhu/AudioAiLaTrieuPhu/batdau2.wav");
            AudioInputStream audio = AudioSystem.getAudioInputStream(file);
            clip = AudioSystem.getClip();
            clip.open(audio);
            clip.start();
        } catch (Exception e) {
        }
    }

    private Clip clipss;

    private void NguoiChoiSanSang() {
        try {
            Scanner sc = new Scanner(System.in);
            File file = new File("src/AiLaTrieuPhu/AudioAiLaTrieuPhu/nguoichoisansang.wav");
            AudioInputStream audio = AudioSystem.getAudioInputStream(file);
            clipss = AudioSystem.getClip();
            clipss.open(audio);
            clipss.start();

        } catch (Exception e) {
        }
    }
    private Clip clipnhacnen;

    private void NhacNen() {
        try {
            File file = new File("src/AiLaTrieuPhu/AudioAiLaTrieuPhu/nhacnencauhoi.wav");
            AudioInputStream audio = AudioSystem.getAudioInputStream(file);
            clipnhacnen = AudioSystem.getClip();
            clipnhacnen.open(audio);
            clipnhacnen.start();
        } catch (Exception e) {
        }
    }
    private Clip clipwin;

    private void Win() {
        try {
            File file = new File("src/AiLaTrieuPhu/AudioAiLaTrieuPhu/traloidung.wav");
            AudioInputStream audio = AudioSystem.getAudioInputStream(file);
            clipwin = AudioSystem.getClip();
            clipwin.open(audio);
            clipwin.start();
        } catch (Exception e) {
        }
    }
    private Clip cliplose;

    private void Lose() {
        try {
            File file = new File("src/AiLaTrieuPhu/AudioAiLaTrieuPhu/traloisai.wav");
            AudioInputStream audio = AudioSystem.getAudioInputStream(file);
            cliplose = AudioSystem.getClip();
            cliplose.open(audio);
            cliplose.start();
        } catch (Exception e) {
        }
    }

    private Clip clipchienthang;

    private void Chienthang() {
        try {
            File file = new File("src/AiLaTrieuPhu/AudioAiLaTrieuPhu/chienthang.wav");
            AudioInputStream audio = AudioSystem.getAudioInputStream(file);
            clipchienthang = AudioSystem.getClip();
            clipchienthang.open(audio);
            clipchienthang.start();
        } catch (Exception e) {
        }
    }

    // khoi tao list -----------
    private static ListCauHoi list1 = new ListCauHoi(); /// thang nay de goi thang listch ben listcauhoi
    private ArrayList<Integer> listold = new ArrayList<>();
    private int diem = 1;
    private int a; /// may cau hoi se dc quyet dinh boi thang a nay 
    private int Giaithuong = 0;
    private String traloi;
    private Clip clipcauhoi; // doc cau hoi 
    /// bo dem thoi gian 
    private static Timer time;
    private int thoigian = 100; //set thoi gian ban dau 
    private int camung50; // dung de cam ung khi nhan 50:50
    private int thoigiancho = 100; // thoi gian load vao game
    private Timer timecho;//timer load vao game

    private void DocCauhoi(ListCauHoi list, int a) {
        try {
            File file = new File(list.listch.get(a).getAudio());
            AudioInputStream audio = AudioSystem.getAudioInputStream(file);
            clipcauhoi = AudioSystem.getClip();
            clipcauhoi.open(audio);
            clipcauhoi.start();
        } catch (Exception e) {
        }
    }

    private int TimSoKhac() {
        int a = -1;
        Random rd = new Random();
        do {
            a = rd.nextInt(list1.listch.size());
        } while (listold.contains(a));
        listold.add(a);
        return a;
    }

    public class LoadTime implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (thoigian > 0) {
                thoigian--;
                jProgressBar1.setValue(thoigian);
            } else {
                txtcauhoi.setText("Hết Giờ Thua Thảm Luôn !");
                txtdap1.setVisible(false);
                txtdap2.setVisible(false);
                txtdap3.setVisible(false);
                txtdap4.setVisible(false);
                btnthoat.setVisible(true);
                btnbatdau.setVisible(true);
                clipnhacnen.stop();
                time.stop();
                thoigian = 100;
                clipcauhoi.stop();
                pnkhangia.setVisible(false);
                jProgressBar1.setVisible(false);
                btn50.setVisible(false);
                btnkhangia.setVisible(false);
                AnhLose.setVisible(true);
                Lose();
            }
        }
    }

    public class LoadTimeVaoGame implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (thoigiancho > 0) {
                thoigiancho--;
            } else {
                clipss.stop();
                timecho.stop();
                thoigiancho = 100;
                listold.clear();
                Giaithuong = 0;
                diem = 1;
                camung50 = 0;
                btnbatdau.setVisible(false);
                btnbatdau.setEnabled(true);
                btnthoat.setVisible(false);
                btntiep.setVisible(false);
                btndung.setVisible(false);
                btntiep.setVisible(false);
                btn50.setVisible(true);
                btnkhangia.setVisible(true);
                /// an 2 cai win voi lose
                Anhwin.setVisible(false);
                AnhLose.setVisible(false);
                // tat man hinh cho de choi game
                manhinhchobatdau.setVisible(false);
            }
        }
    }

    private void ChienThangTroChoi() {
        if (diem > 15) {
            Chienthang();
            txtcauhoi.setText("Chúc Bạn Bạn Đã Chiến Thắng + " + Giaithuong + "$");
            btntiep.setVisible(false);
            btndung.setVisible(false);
            btnbatdau.setVisible(true);
            btnthoat.setVisible(true);
            txtsocauhoi.setVisible(false);
            try {
                TimeUnit.SECONDS.sleep(1);
            } catch (Exception e) {
            }
            Anhwin.setVisible(true);
        }
    }

    private void ThuaTrochoi() {
        Lose();
        txtdap1.setVisible(false);
        txtdap2.setVisible(false);
        txtdap3.setVisible(false);
        txtdap4.setVisible(false);
        jProgressBar1.setVisible(false);
        txtcauhoi.setText("Thua Rồi Không 1 Xu Dính Túi !");
        btnbatdau.setVisible(true);
        btnthoat.setVisible(true);
        AnhLose.setVisible(true);
    }
//    public static void GoiCauHoi(ListCauHoi list) {
//        Random rd = new Random();
//        do {
//            int a=rd.nextInt(list.listch.size());
//            if(!listold.contains(a))
//            {
//                listold.add(a);
//                DocCauhoi(list, a);
//            }
//        } while (diem > 0 || diem == 10);
//    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ALTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ALTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ALTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ALTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // khoi tao form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ALTP aila = new ALTP();
                aila.setVisible(true);
                aila.setLocationRelativeTo(null);
            }
        });
        list1.KhoiTaoCauHoi();
        batdau();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnhLose;
    private javax.swing.JLabel Anhwin;
    private javax.swing.JLabel btn50;
    private javax.swing.JButton btnbatdau;
    private javax.swing.JButton btndung;
    private javax.swing.JLabel btnkhangia;
    private javax.swing.JButton btnthoat;
    private javax.swing.JButton btntiep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBarA;
    private javax.swing.JProgressBar jProgressBarB;
    private javax.swing.JProgressBar jProgressBarC;
    private javax.swing.JProgressBar jProgressBarD;
    private javax.swing.JLabel lbphantramA;
    private javax.swing.JLabel lbphantramB;
    private javax.swing.JLabel lbphantramC;
    private javax.swing.JLabel lbphantramD;
    private javax.swing.JLabel manhinhchobatdau;
    private javax.swing.JPanel pnkhangia;
    private javax.swing.JTextArea txtcauhoi;
    private javax.swing.JButton txtdap1;
    private javax.swing.JButton txtdap2;
    private javax.swing.JButton txtdap3;
    private javax.swing.JButton txtdap4;
    private javax.swing.JLabel txtsocauhoi;
    // End of variables declaration//GEN-END:variables
}
